name: "Fuzzer"
on: workflow_dispatch
jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
      - name: run fuzzer 
        run: |
          python3 fuzz.py
        shell: bash
