name: Fuzzer
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  autoFuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: setup python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip3 install --upgrade pip
        
      - name: run fuzzer 
        run: cd /home/runner/work/Foster_Mitchell-SQA2022-AUBURN/TestOrchestrator4ML-main
      - run: ls
