name: Fuzzer
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  autoFuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: setup python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install astdump
          pip3 install pandas
          pip3 install tensorflow
          pip3 install scikit-learn
          pip3 install matplotlib
          pip3 install keras
          
      - name: run fuzzer 
        working-directory: ./TestOrchestrator4ML-main
        run: python3 fuzz.py
